# Generated by Django 3.0.7 on 2021-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(default='', max_length=20)),
                ('seller_pass', models.CharField(default='', max_length=25)),
                ('seller_address', models.CharField(default='', max_length=30)),
                ('seller_tele', models.CharField(default='', max_length=15)),
                ('seller_email', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Sellerinfo',
            },
        ),
    ]
