# Generated by Django 3.0.7 on 2021-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterSeller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinfo',
            name='seller_sex',
            field=models.CharField(default='', max_length=2),
        ),
    ]
