# Generated by Django 3.0.7 on 2021-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20)),
                ('user_pass', models.CharField(default='', max_length=25)),
                ('user_address', models.CharField(default='', max_length=30)),
                ('user_tele', models.CharField(default='', max_length=15)),
                ('user_email', models.CharField(default='', max_length=20)),
                ('user_sex', models.CharField(default='', max_length=2)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
