# Generated by Django 3.0.7 on 2021-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=10)),
                ('product_type', models.CharField(default='', max_length=10)),
                ('product_info', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'productinfo',
            },
        ),
    ]
