# Generated by Django 3.0.7 on 2021-01-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='product_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='product_info',
            field=models.CharField(default='', max_length=30),
        ),
    ]
