# Generated by Django 3.0.7 on 2021-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210107_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='seller_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
