# Generated by Django 3.0.7 on 2021-01-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productsinfo_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinfo',
            name='product_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
