# Generated by Django 3.0.7 on 2021-01-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210107_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinfo',
            name='product_info',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
