# Generated by Django 3.0.7 on 2021-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210107_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
