# Generated by Django 3.0.7 on 2021-01-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_productsinfo_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinfo',
            name='product_info',
            field=models.CharField(default='', max_length=150),
        ),
    ]
