# Generated by Django 3.0.7 on 2021-01-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_productsinfo_product_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfo',
            name='product_img_url',
        ),
    ]
