# Generated by Django 3.0.7 on 2021-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_productsinfo_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='product_img_url',
            field=models.CharField(default='assets/goods/.jpg', max_length=30),
        ),
    ]
